version: '3.8'

services:
  mt5-docker-api:
    image: jsfrnc/mt5-docker-api:latest
    # For local testing, uncomment the following line and comment the above
    # image: mt5-docker-api:test
    container_name: mt5-docker-api
    restart: unless-stopped
    ports:
      - "3009:3009"  # VNC Web Access
      - "8009:8009"  # REST API
      - "8009:8008"  # Python MT5 API
    volumes:
      - mt5_data:/root/.wine/drive_c/Program Files/MetaTrader 5
      - ./logs:/app/logs
    environment:
      - MT5_LOGIN=${MT5_LOGIN}
      - MT5_PASSWORD=${MT5_PASSWORD}
      - MT5_SERVER=${MT5_SERVER}
      - API_KEY=${API_KEY:-your-secure-api-key}
      - VNC_PASSWORD=${VNC_PASSWORD:-vnc123}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mt5-network

volumes:
  mt5_data:
    driver: local

networks:
  mt5-network:
    driver: bridge